<?php
pdo_query("CREATE TABLE IF NOT EXISTS `ims_amouse_wxapp_house` (
`id` int(10) NOT NULL AUTO_INCREMENT,
`uniacid` int(10) NOT NULL,
`openid` varchar(255) NOT NULL,
`avater` varchar(255) NOT NULL,
`nickname` varchar(255) NOT NULL,
`mobile` varchar(18) COMMENT '手机号',
`title` varchar(255) COMMENT '房屋名称',
`code` varchar(255) NOT NULL,
`is_person` tinyint(2) DEFAULT '0' COMMENT '0:官方 1：个人',
`person_mobile` varchar(18) DEFAULT '0' COMMENT '个人电话',
`price` varchar(100) COMMENT '单价',
`total_price` varchar(100) COMMENT '总价',
`rental` varchar(100) COMMENT '租金元/月',
`house_type` tinyint(2) DEFAULT '0' COMMENT '0:出租 1：出售 2:求租3：求购',
`cash_type` varchar(100) COMMENT '押金类型',
`estate` varchar(255) COMMENT '小区名',
`video_url` varchar(255) COMMENT '视频链接',
`area_id` int(10) NOT NULL COMMENT '区域',
`type_id` int(10) NOT NULL COMMENT '户型',
`fit_id` int(10) NOT NULL COMMENT '装修情况',
`use_id` int(10) NOT NULL COMMENT '用途',
`shop_id` int(10) NOT NULL COMMENT '门店',
`vill_id` int(10) NOT NULL COMMENT '小区',
`view` int(10) NOT NULL DEFAULT '0' COMMENT '阅读量',
`age_id` int(10) NOT NULL COMMENT '年代',
`house_toward` int(10) NOT NULL COMMENT '方向',
`agent_id` int(10) NOT NULL COMMENT '经纪人',
`is_open_map` tinyint(1) DEFAULT '1' COMMENT '0打开 1关闭',
`lat` decimal(18,10) NOT NULL DEFAULT '31.9591530000' COMMENT '经度',
`lng` decimal(18,10) NOT NULL DEFAULT '118.7512210000' COMMENT '纬度',
`house_area` varchar(100) COMMENT '面积',
`floor` varchar(100) COMMENT '楼层',
`desc` varchar(255),
`address` varchar(255),
`imgs` text,
`vipstatus` tinyint(1) NOT NULL DEFAULT '0',
`listorder` int(10) DEFAULT '0' COMMENT '排序',
`createtime` int(10) NOT NULL,
`status` tinyint(1) DEFAULT '0' COMMENT '0表示未审核，1表示已审核，2表示禁用',
`sendcode` varchar(255) COMMENT '推送码',
`document_age` varchar(10) NOT NULL COMMENT '产证日期',
`house_age` varchar(20) NOT NULL COMMENT '建造年代',
KEY `indx_weid` (`uniacid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_amouse_wxapp_house_history` (
`id` int(10) NOT NULL AUTO_INCREMENT,
`uniacid` int(10) NOT NULL,
`cardid` int(10) NOT NULL,
`from_user` varchar(255) NOT NULL COMMENT '自己',
`zan_mid` int(10) NOT NULL,
`zan_cid` int(10) NOT NULL,
`to_user` varchar(255) NOT NULL COMMENT '好友',
`sms_type` tinyint(2) NOT NULL COMMENT '0:看，1:赞 2:收藏',
`createtime` int(11) NOT NULL,
KEY `indx_weid` (`uniacid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

");
